ROWS = 15
COLUMS = 15
TILE_SIZE = 48
SIDE_PANEL = 300

SCREEN_HEIGHT = TILE_SIZE * COLUMS
SCREEN_WIDTH = TILE_SIZE * ROWS
FPS = 60
HEALTH = 100
COINS = 650


# enemy constants
SPAWN_COOLDOWN = 400

# turret
TURRET_LEVEL = 4
BUY_COST = 200
UPGRADE_COST = 100
KILL_REWARD = 1
ANIMATION_STEPS = 8
ANIMATION_DELAY = 15
TURRET_DAMAGE = 5