ROWS = 15
COLUMS = 15
TILE_SIZE = 48
SIDE_PANEL = 300

SCREEN_HEIGHT = TILE_SIZE * COLUMS
SCREEN_WIDTH = TILE_SIZE * ROWS
FPS = 60


# enemy constants
SPAWN_COOLDOWN = 400

# turret
ANIMATION_STEPS = 8
ANIMATION_DELAY = 15
